#!/bin/bash
set -euo pipefail

export UBERCONF_PATH=/config/config.yaml
export STORAGE_DIR=/config/connector
export OVERSEERR_CONFIG_PATH=/config/overseerr/settings.json
export OVERSEERR_HOST=http://localhost:5055

(
	cd /app/connector
	pnpm start
)
