name: Run Node tests on Connector

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./connector
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.6
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: ./connector/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm prisma generate
      - run: pnpm tsc
      - run: pnpm test
      - run: pnpm lint
